version: '3.7'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: incidencias
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql+psycopg2://dev:devpass@db:5432/incidencias
